// ========================================================
// MINI APP EXPLAINERS CATALOG
// Plain-English explainers for viewers who have NOT yet subscribed.
// Explains the problem they face, what each pill unlocks, and the free value.
// ========================================================

export const MINI_APP_EXPLAINERS = [
  {
    id: 'charlie',
    number: 1,
    title: 'Charlie AI',
    subtitle: 'Live 2-Way Voice Concierge',
    badge: 'VOICE AI',
    badgeCount: 1,
    iconName: 'Mic',
    route: '/talking-app',
    tagline: 'Talk naturally out loud — no typing, no spam, no bots selling your data.',
    theProblem: 'Traditional real estate portals (Zillow, Realtor.com) force you into web forms and immediately auction your phone number to 5+ aggressive sales agents who represent the seller, not you.',
    theFiduciarySolution: 'Charlie Simmons is our 24/7 spoken voice concierge powered by Gemini Live. Speak naturally to compare cost of living, audit destination school districts, calculate tax migration savings, or vet any listing across all 50 states.',
    unsubscribedAccess: 'Free guest questions anytime. Tap the microphone and experience live conversational voice-to-voice real estate intelligence.',
    subscriberUnlock: 'Unlimited 2-way voice debriefs, custom relocation roadmap generation, and automatic audio transcripts saved to your private file vault.',
    keyActionLabel: 'Talk with Charlie Now',
  },
  {
    id: 'roadmap',
    number: 2,
    title: 'Roadmaps',
    subtitle: 'Move Milestones & Escrow Flight Plan',
    badge: 'FLIGHT PLAN',
    badgeCount: 3,
    iconName: 'Compass',
    route: '/client-roadmap',
    tagline: 'A 40-step flight plan coordinating your move from decision to keys in hand.',
    theProblem: 'Moving out of state involves over 40 complex milestones across two states. Buyers frequently miss contingency removal dates, rate lock deadlines, or utility transfer schedules, leading to costly escrow delays.',
    theFiduciarySolution: 'Our interactive Relocation Roadmap sequences every phase: agent vetting, comparative market analysis, offer structuring, home inspection auditing, escrow milestones, packing logistics, and utility turn-on.',
    unsubscribedAccess: 'Full interactive preview of the 5-phase relocation milestone sequence and fiduciary checklist.',
    subscriberUnlock: 'A live, personalized transaction roadmap synced to your specific closing dates with automated deadline reminders and agent accountability.',
    keyActionLabel: 'Explore Relocation Roadmap',
  },
  {
    id: 'calendar',
    number: 3,
    title: 'Calendar',
    subtitle: 'Move Dates & Critical Deadlines',
    badge: 'DEADLINES',
    badgeCount: null,
    iconName: 'Calendar',
    route: '/calendar',
    isMiniApp: true,
    tagline: 'Never miss a 1031 exchange cutoff, inspection deadline, or mover arrival.',
    theProblem: 'Real estate contracts carry strict legal deadlines (earnest money deposits, loan approval, physical inspection contingency removal). Missing a deadline by 24 hours can forfeit thousands in deposits.',
    theFiduciarySolution: 'A dedicated relocation calendar pre-populated with your contract timeline, 1031 exchange 45-day identification milestones, mover arrival windows, and school enrollment dates.',
    unsubscribedAccess: 'Interactive move timeline calculator and sample milestone calendar.',
    subscriberUnlock: 'Direct 1-click sync to your personal Google Calendar, Apple iCal, or Outlook with push notifications.',
    keyActionLabel: 'Open Move Calendar',
  },
  {
    id: 'email',
    number: 4,
    title: 'Email',
    subtitle: 'Private Concierge Inbox',
    badge: 'SECURE',
    badgeCount: 1,
    iconName: 'Mail',
    route: '/email',
    isMiniApp: true,
    tagline: 'Your private email firewall protecting you from unwanted agent solicitations.',
    theProblem: 'The moment you enter your real email on public real estate sites, your inbox is flooded with automated drip campaigns, junk property alerts, and persistent listing agent pitches.',
    theFiduciarySolution: 'A private communications hub that shields your personal inbox. All communications with your fiduciary coordinator, vetted destination agent, and closing attorney route securely through here.',
    unsubscribedAccess: 'Preview our zero-spam privacy guarantee and sample communication dispatch protocol.',
    subscriberUnlock: 'Dedicated subscriber concierge inbox with 1-click messaging to Bob Dyson and your hand-selected vetted agent.',
    keyActionLabel: 'View Private Inbox',
  },
  {
    id: 'calculator',
    number: 5,
    title: 'Calculator',
    subtitle: 'State Tax & Relocation Math',
    badge: 'FINANCIAL',
    badgeCount: null,
    iconName: 'Calculator',
    route: '/calculator',
    isMiniApp: true,
    tagline: 'Calculate net take-home pay, state tax savings, and real estate purchasing power.',
    theProblem: 'Buyers often calculate mortgage payments without factoring in state income tax variances, local property assessment caps (e.g. CA Prop 13 vs TX appraisals), or home insurance differences.',
    theFiduciarySolution: 'An all-in-one financial modeling tool. Compare your current take-home pay against your destination state, calculate capital gains exemptions ($500k married), and see your exact monthly payment.',
    unsubscribedAccess: 'Full interactive mortgage and state income tax comparison calculator with live sliders.',
    subscriberUnlock: 'Save customized financial profiles, export lender-ready debt-to-income worksheets, and share with your CPA.',
    keyActionLabel: 'Launch Financial Calculator',
  },
  {
    id: 'weather',
    number: 6,
    title: 'Weather',
    subtitle: 'Origin vs. Target Climate Comparison',
    badge: 'CLIMATE',
    badgeCount: null,
    iconName: 'CloudSun',
    route: '/weather',
    isMiniApp: true,
    tagline: 'Compare year-round temperatures, humidity, sunshine, and seasonal shifts.',
    theProblem: 'Many relocating families move to a new state in the spring only to be shocked by 115° summer heat, 90% humidity, or severe winter ice storms that they never experienced during a weekend visit.',
    theFiduciarySolution: 'Side-by-side climate intelligence. Compares your origin city against target destinations for average highs/lows by month, air quality index, annual sunny days, and severe weather risks.',
    unsubscribedAccess: 'Live weather search and historical climate comparisons between any two U.S. cities.',
    subscriberUnlock: 'Pin your top 3 destination cities for real-time weather alerts and seasonal acclimatization tips.',
    keyActionLabel: 'Compare City Climates',
  },
  {
    id: 'strategy',
    number: 7,
    title: 'Strategy',
    subtitle: 'Tax & Solutions Battleplan',
    badge: 'TAX STRATEGY',
    badgeCount: null,
    iconName: 'Sparkles',
    route: '/solutions',
    tagline: 'Customized blueprints for capital gains avoidance and dual-state residency audits.',
    theProblem: 'Leaving high-tax states like California, New York, or Illinois requires strict documentation to defeat state franchise tax residency audits. Improper timing can trigger retrospective tax penalties.',
    theFiduciarySolution: 'Our proprietary Solutions Map matches your move profile with proven strategies: 1031 tax-deferred exchanges, primary residence exclusion timing, corporate entity relocation, and safe-harbor residency cutoffs.',
    unsubscribedAccess: 'Explore the full Tax & Relocation Strategy Solutions Map with sample scenarios.',
    subscriberUnlock: 'Request a custom AI-generated strategy road map reviewed by our fiduciary team.',
    keyActionLabel: 'Explore Strategy Solutions',
  },
  {
    id: 'vet',
    number: 8,
    title: 'Vet Listing',
    subtitle: 'Fiduciary Second Opinion Audit',
    badge: 'INDEPENDENT',
    badgeCount: null,
    iconName: 'ShieldCheck',
    route: '/refer',
    tagline: 'Paste any Zillow, Redfin, or Realtor.com link for an independent, unbiased review.',
    theProblem: 'Listing agents on Zillow are legally obligated to get the SELLER the highest price possible. When you ask them about the home, they highlight the pros and minimize the structural and neighborhood flaws.',
    theFiduciarySolution: 'Paste any property link or address into our vetting engine. We pull public property records, permit histories, flood zone designations, and neighborhood comps to give you the honest truth.',
    unsubscribedAccess: 'Submit any single address for a complimentary fiduciary second-opinion audit.',
    subscriberUnlock: 'Priority multi-property vetting queue with direct agent disclosure review and contract guidance.',
    keyActionLabel: 'Vet a Property Address',
  },
  {
    id: 'library',
    number: 9,
    title: 'My Library',
    subtitle: 'Vault & Real Estate Deeds',
    badge: 'VAULT',
    badgeCount: 4,
    iconName: 'BookOpen',
    route: '/media',
    tagline: 'Encrypted cloud storage for your deeds, title reports, and move agreements.',
    theProblem: 'During a cross-country move, critical documents (preliminary title reports, grant deeds, home warranties, inspection repair addendums) get scattered across emails, text messages, and portal logins.',
    theFiduciarySolution: 'A clean, bank-grade document vault. Every report Charlie generates, every vetted agent agreement, and every closing document is stored securely in one place with 1-click download access.',
    unsubscribedAccess: 'Browse our free educational library of relocation guides, checklists, and fiduciary whitepapers.',
    subscriberUnlock: 'Private cloud storage allocated exclusively for your family’s real estate transactions and deed archives.',
    keyActionLabel: 'Open Document Library',
  },
  {
    id: 'news',
    number: 10,
    title: 'DNN News',
    subtitle: 'Daily 6AM Housing Intelligence',
    badge: 'BROADCAST',
    badgeCount: 11,
    iconName: 'Play',
    route: '/dnn-news',
    tagline: 'Televised morning video briefs on mortgage rates, Fed moves, and housing shifts.',
    theProblem: 'Mainstream financial news is generic, sensationalized, and published weeks after market shifts happen, leaving buyers and sellers with outdated information.',
    theFiduciarySolution: 'The Dyson News Network (DNN) broadcasts every weekday at 6:00 AM PT. Anchors Charlie Simmons and Bob Dyson break down real-time 30-year fixed rates, inventory trends, and interstate migration data in 2-minute video clips.',
    unsubscribedAccess: 'Watch today’s televised broadcast and browse the national news headline archive for free.',
    subscriberUnlock: 'Daily morning email brief with hyper-local market pulse commentary tailored to your destination city.',
    keyActionLabel: 'Watch DNN 6AM Broadcast',
  },
  {
    id: 'agent',
    number: 11,
    title: 'My Agent',
    subtitle: 'Vetted Destination Broker',
    badge: 'TOP 1%',
    badgeCount: null,
    iconName: 'Users',
    route: '/my-agent',
    tagline: 'Hand-selected, independent destination agents who represent YOU — never the seller.',
    theProblem: 'Over 80% of real estate agents are part-time or pay marketing portals for your contact info. Choosing the wrong agent in an unfamiliar destination can cost you tens of thousands in overpayment.',
    theFiduciarySolution: 'We curate the top 1% of producing independent agents across all 50 states. We interview them, verify their track record, confirm zero dual-agency conflicts, and hold them strictly accountable to your timeline.',
    unsubscribedAccess: 'Review our 7-point fiduciary agent vetting standards and directory of partner markets.',
    subscriberUnlock: 'Direct VIP introduction to your personal vetted agent with our fiduciary oversight at zero fee to you.',
    keyActionLabel: 'See Vetting Standards',
  },
  {
    id: 'refer',
    number: 12,
    title: 'Refer Lead',
    subtitle: 'Refer a Buyer & Earn 25%',
    badge: '25% PAYOUT',
    badgeCount: 2,
    iconName: 'ArrowRight',
    route: '/refer',
    tagline: 'Connect a relocating client, colleague, or friend and track the deal to closing.',
    theProblem: 'Sending an out-of-state referral to an unknown agent is a gamble. Referral fees get forgotten, clients get neglected, and the referring party is left in the dark.',
    theFiduciarySolution: 'A formal Private Referral Network (PRN) engine. Submit relocating buyers, sellers, or colleagues. We execute legal referral agreements, assign top vetted agents, manage the escrow, and disburse 25% referral fees at closing.',
    unsubscribedAccess: 'Anyone can submit a relocation referral and receive a tracking confirmation.',
    subscriberUnlock: 'Real-time referral milestone tracking dashboard with automated closing notifications and escrow fee ledger.',
    keyActionLabel: 'Submit a Referral',
  },
  {
    id: 'concierge',
    number: 13,
    title: 'Concierge Direct',
    subtitle: 'Direct Cellular Line: (858) 353-1200',
    badge: 'HUMAN DESK',
    badgeCount: null,
    iconName: 'Phone',
    route: 'tel:+18583531200',
    tagline: 'Direct cellular access to Bob Dyson — no call centers, no automated phone trees.',
    theProblem: 'When an urgent issue happens in an escrow or move, automated customer support tickets take 24–48 hours to reply.',
    theFiduciarySolution: 'Direct cellular and 2-way SMS access to Bob Dyson and our executive California concierge desk. Over 55 years of continuous real estate leadership at your fingertips.',
    unsubscribedAccess: 'Open to any visitor needing urgent fiduciary guidance or second-opinion advice.',
    subscriberUnlock: 'Priority client routing with dedicated concierge callback guarantee within 15 minutes.',
    keyActionLabel: 'Call (858) 353-1200',
  },
];