import React from 'react';
import ChiefPilotHowItWorks from './ChiefPilotHowItWorks';
import ChiefPilotExampleFrame from './ChiefPilotExampleFrame';

const CHECKS = ['Local market experience', 'Recent buyer-side performance', 'Communication and availability', 'References, fit, and transaction support'];
const STEPS = ['Understand the buyer’s location, property, and working preferences.', 'Review local experience, performance, and references.', 'Save a vetted-introduction intent under the Preferred Client record.', 'CoPilot stays alongside the buyer and agent as a supportive partner.'];

export default function ChiefPilotAgentVetting({ title, activeProperty, hasOwnProperty, isExample, onHideExample, onSearchOwn, introStatus, onRequestIntro }) {
  const market = activeProperty ? [activeProperty.address?.city || activeProperty.city?.split(',')[0], activeProperty.address?.state].filter(Boolean).join(', ') : '';
  const sample = <div><p className="text-sm text-dyson-text">Market: {market || 'not available in example'}</p><ul className="mt-4 space-y-3">{CHECKS.map(item => <li key={item} className="border-l border-white/15 pl-3"><p className="text-sm text-dyson-text">{item}</p><p className="mt-1 text-xs text-dyson-taupe">Review evidence, interview fit, and unresolved questions before choosing.</p></li>)}</ul></div>;
  const next = <div><button type="button" onClick={hasOwnProperty ? onRequestIntro : onSearchOwn} disabled={introStatus === 'saving' || introStatus === 'saved'} className="rounded-md border border-white/20 px-4 py-2 text-sm text-dyson-text disabled:opacity-40">{hasOwnProperty ? introStatus === 'saving' ? 'Saving…' : introStatus === 'saved' ? 'Intent saved' : 'Request vetted intro' : 'Search your own property first'}</button>{introStatus === 'gate' && <p className="mt-3 text-sm text-dyson-taupe">Claim Preferred Client status to save this private introduction intent.</p>}{introStatus === 'saved' && <p className="mt-3 text-sm text-dyson-taupe">Intent saved for review. No email or text was sent.</p>}</div>;
  return <div><h2 className="text-2xl font-normal text-dyson-text">{title}</h2><ChiefPilotExampleFrame isExample={isExample} purpose="Choose a local agent who fits while CoPilot stays alongside you as a supportive partner under the referral agreement." benefit="Clear checks to use before you interview or select anyone." onHide={onHideExample} onSearchOwn={onSearchOwn} sample={sample} next={next} /><ChiefPilotHowItWorks items={STEPS} /></div>;
}