const closingRebate = { id: 'closing_rebate', label: 'How does Dyson & Dyson protect buyers?', speaker: 'bob', speakerName: 'Bob Dyson', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/3400475d9_bobanswer_6a5d2e96818523aa8749508e.mp4' };
const hiddenRisks = { id: 'hidden_risks', label: 'How do you find hidden property risks?', speaker: 'charlie', speakerName: 'Charlie Simmons', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/6f622bb1c_charlie_avatar_clean_vet.mp4' };
const whoIsDyson = { id: 'who_is_dyson', label: 'Who is Dyson & Dyson?', speaker: 'bob', speakerName: 'Bob Dyson', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/a4a2013f3_bobanswer_6a5d2e96818523aa87495089.mp4' };
const bobSolutionsTraps = { id: 'bob_solutions_traps', label: "Bob's Take: Escrow & Deal Traps", speaker: 'bob', speakerName: 'Bob Dyson', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/94b83e0f7_reqa_6a5272697665dffe7b165e0d_bob.mp4' };

const vettedAgentWhyItMatters = { id: 'vetted_agent_intro', label: 'Why agent vetting matters', speaker: 'charlie', speakerName: 'Charlie Simmons', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/b95793102_vettedagent_6a53dec057bea564d344fbf0_charlie.mp4' };
const destinationAgentMatch = { id: 'destination_agent_match', label: 'How do you match a client to the right destination agent?', speaker: 'bob', speakerName: 'Bob Dyson', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/b7dce5021_vetdesk_6a52839606e00cdc06b05e2c_bob.mp4' };

const relocationManagerVsAgent = { id: 'relo_manager_vs_agent', label: 'Relocation manager vs. a standard agent', speaker: 'bob', speakerName: 'Bob Dyson', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/de2982d9a_reqa_6a5272697665dffe7b165e0a_bob.mp4' };

const roadmapPhase1Charlie = { id: 'roadmap_p1_charlie', label: 'Phase 1: Onboarding & Profile', speaker: 'charlie', speakerName: 'Charlie Simmons', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/cda96891a_roadmap_6a52cbc75ead5c9873240cd0_charlie.mp4' };
const roadmapPhase1Bob = { id: 'roadmap_p1_bob', label: 'What happens the moment I come aboard?', speaker: 'bob', speakerName: 'Bob Dyson', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/c57834779_roadmap_6a52cbc75ead5c9873240cd0_bob.mp4' };

const roadmapPhase7Charlie = { id: 'roadmap_p7_charlie', label: 'Phase 7: Escrow & Closing', speaker: 'charlie', speakerName: 'Charlie Simmons', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/989a2a107_roadmap_6a52cbc75ead5c9873240cd6_charlie.mp4' };
const roadmapPhase7Bob = { id: 'roadmap_p7_bob', label: 'How do you keep deals from falling apart?', speaker: 'bob', speakerName: 'Bob Dyson', videoUrl: 'https://base44.app/api/apps/69d905d72ff7c93b5ef050c4/files/mp/public/69d905d72ff7c93b5ef050c4/8a0f86372_roadmap_6a52cbc75ead5c9873240cd6_bob.mp4' };

const BUY_STEPS = ['Browse your preferred MLS and copy the MLS# or address', 'Paste the address into CoPilot', 'AI + human analysis of the property', 'Intelligence delivered: comps, risks, and rebate insights', 'Make a better, more confident decision'];

export const SUBJECT_EXPLAINER_CONTENT = {
  'relocation-management': { explainers: [relocationManagerVsAgent, whoIsDyson], byline: "After 55 years in Corporate Relocation Nationwide, we are providing those same services to our Private Clients in all markets. Same attention to detail with concierge-style service that Corporate Relo Clients expect. Today, we accomplish our services with the assistance of 21 AI Assistants in a wonderful fully transparent approach to real estate transactions.", intro: 'Now, Lets turn a real estate objective into an accountable plan before decisions are made.', bullets: ['Define the objective and decision criteria', 'Separate verified facts from unresolved questions', 'Assign the right specialist and next action'], milestones: ['Objective', 'Research', 'Options', 'Strategy', 'Decision'] },
  'real-estate-solutions': { explainers: [closingRebate, hiddenRisks, whoIsDyson, bobSolutionsTraps], intro: 'Now, Lets turn a real estate objective into an accountable plan before decisions are made.', bullets: ['Define the objective and decision criteria', 'Separate verified facts from unresolved questions', 'Assign the right specialist and next action'], milestones: ['Objective', 'Research', 'Options', 'Strategy', 'Decision'] },
  'buy': { explainers: [closingRebate, hiddenRisks, whoIsDyson, bobSolutionsTraps], preface: 'It all starts with searching for properties in your chosen communities. Followed by these 5 steps:', steps: BUY_STEPS, intro: 'Now, Lets turn a real estate objective into an accountable plan before decisions are made.', bullets: ['Define the objective and decision criteria', 'Separate verified facts from unresolved questions', 'Assign the right specialist and next action'], milestones: ['Objective', 'Research', 'Options', 'Strategy', 'Decision'] },
  'property-search': { explainers: [hiddenRisks], intro: 'Move from a broad search to a defensible property shortlist.', bullets: ['Set location, price, and property requirements', 'Compare listings using the same decision criteria', 'Flag open risks before selecting a property'], milestones: ['Criteria', 'Listings', 'Compare', 'Shortlist', 'Select'] },
  'property-audit': { explainers: [hiddenRisks, closingRebate], intro: 'Organize independent diligence around the property under consideration.', bullets: ['Review available records and disclosures', 'Frame pricing, condition, and location risks', 'Create questions for licensed specialists'], milestones: ['Records', 'Risks', 'Comps', 'Questions', 'Brief'] },
  'agent-vetting': { explainers: [vettedAgentWhyItMatters, destinationAgentMatch], intro: 'Evaluate agent fit for the market, objective, and required diligence.', bullets: ['Confirm local buyer-side experience', 'Review communication and accountability fit', 'Surface conflicts before an introduction'], milestones: ['Market Fit', 'Experience', 'Conflicts', 'Interview', 'Select'] },
  'team-thread': { explainers: [relocationManagerVsAgent, whoIsDyson], intro: 'Keep the client, local agent, and Dyson oversight in one decision record.', bullets: ['Capture the client question or instruction', 'Add the local agent update and evidence', 'Record the decision and accountable next step'], milestones: ['Client Ask', 'Agent Update', 'Dyson Review', 'Decision', 'Record'] },
  'move-roadmap': { explainers: [relocationManagerVsAgent, whoIsDyson], intro: 'Translate the relocation objective into a visible sequence of accountable work.', bullets: ['Define timing, dependencies, and owners', 'Track readiness before each transition', 'Keep the client focused on the next milestone'], milestones: ['Discovery', 'Property Search', 'Agent Match', 'Offer', 'Escrow', 'Move', 'Close'] },
  'escrow-watch': { explainers: [roadmapPhase7Charlie, roadmapPhase7Bob], intro: 'Make key escrow deadlines and unresolved issues visible before they become surprises.', bullets: ['Track disclosures, inspections, and financing', 'Identify the owner of every unresolved item', 'Protect contingency and decision deadlines'], milestones: ['Open', 'Disclosures', 'Inspect', 'Finance', 'Contingencies', 'Close'] }
};