import { 
  Newspaper, GitBranch, ClipboardList, MapPin, Building2, SendHorizontal, 
  Video, Edit, Library, Clapperboard, Zap, BarChart3, Users, Send, Shield, 
  BookOpen, Star, FileCheck, DollarSign, Archive, ArrowRight, Sparkles,
  Map, ShieldCheck, FileSearch, Home, ShoppingBag, TrendingUp, Calendar,
  MessageCircle, Fingerprint, List, ExternalLink, Play, Mail, MessageSquare, CheckCircle2, Inbox, Clock,
  Calculator, CloudSun, Mic, Brain, Compass, Thermometer, Phone, ScrollText,
  Monitor, Plug, Megaphone, FileText, LayoutDashboard, Layers, Package, Search
} from 'lucide-react';

export const DEPARTMENT_DATA = {
  dnn: {
    id: 'dnn',
    name: 'DNN News & Intelligence',
    subtitle: 'Morning broadcast production, daily video library, and media intelligence',
    icon: Newspaper,
    accentColor: '#ef4444',
    badge: 'DAILY BROADCAST',
    subChoices: [
      {
        id: 'broadcast_production',
        title: 'Studio & Broadcast Production',
        tagline: 'Video renders, pipelines, and script generation',
        icon: Clapperboard,
        color: '#ef4444',
        badge: 'ACTIVE RENDER',
        description: 'Manage the automated 6AM morning brief, script reviews, video previews, and render credit quotas.',
        primaryLink: { label: 'Open Daily Library', path: '/admin/dnn/daily-library' },
        links: [
          { label: '📚 Daily News Library', path: '/admin/dnn/daily-library', highlight: true },
          { label: '🎬 Video Preview & Blast', path: '/admin/dnn/video-preview' },
          { label: '✏️ Script Studio (Templates & Preview)', path: '/admin/dnn/script-studio', highlight: true },
          { label: '🎬 Show Production Pipeline', path: '/admin/dnn/show-pipeline' },
          { label: '⚡ Pipeline Credit Monitor', path: '/admin/heygen-credits' },
          { label: '📊 Production Cost Dashboard', path: '/admin/production-dashboard' },
        ],
      },
      {
        id: 'news_intel',
        title: 'News Feed & Market Intelligence',
        tagline: 'Staged market articles, data feeds, and archive',
        icon: Newspaper,
        color: '#f59e0b',
        badge: 'REAL-TIME DATA',
        description: 'Curate local and national housing stories, federal reserve decisions, and tax migration data.',
        primaryLink: { label: 'Explore News Feed', path: '/admin/dnn/news-feed' },
        links: [
          { label: '📰 News Feed (Staging Desk)', path: '/admin/dnn/news-feed', highlight: true },
          { label: '📊 Market Data Hub', path: '/admin/dnn/market-data' },
          { label: '📺 Broadcast Archive Page', path: '/dnn-archive' },
          { label: '📖 Bureau Story Hub', path: '/admin/dnn/bureau-stories' },
          { label: '🎥 Explainer Video Sets', path: '/admin/dnn/explainer-videos' },
        ],
      },
      {
        id: 'subscribers_bureau',
        title: 'Subscribers & Agent Bureau',
        tagline: 'Subscriber CRM, communications, and co-branding',
        icon: Users,
        color: '#3b82f6',
        badge: 'B2B SYNDICATION',
        description: 'Track audience growth, agent syndication channels, and private-label morning broadcast dispatches.',
        primaryLink: { label: 'Open Subscriber CRM', path: '/admin/dnn/subscribers' },
        links: [
          { label: '👥 Subscriber CRM', path: '/admin/dnn/subscribers', highlight: true },
          { label: '📨 Communications Hub', path: '/admin/dnn/communications' },
          { label: '🛡️ Agent Bureau (B2B)', path: '/admin/dnn/agent-bureau' },
          { label: '📣 Agent Recruiting Broadcast', path: '/admin/dnn/recruiting' },
          { label: '📈 Featured Agent Revenue', path: '/admin/dnn/revenue' },
        ],
      },
      {
        id: 'studio_landing',
        title: 'Studio Landing & Verified 16:9',
        tagline: 'Verified studio set design, layout, and master source',
        icon: Video,
        color: '#10b981',
        badge: 'LOCKED SPEC',
        description: 'Preview and inspect the verified 16:9 studio desk layout, Charlie anchor composites, and locked source code.',
        primaryLink: { label: 'View Verified Studio', path: '/admin/archived/studio-landing' },
        links: [
          { label: '✅ DNN Studio Landing Page (Verified)', path: '/admin/archived/studio-landing', highlight: true },
          { label: '🔒 Locked Source Code', path: '/admin/dnn/studio-landing-source' },
          { label: '✅ Locked Final Look (Charlie Solution)', path: '/admin/dnn/charlie-studio-solution' },
          { label: '📊 DNN Flow Chart', path: '/admin/workflows/dnn' },
        ],
      },
    ],
  },
  workflows: {
    id: 'workflows',
    name: 'Workflows & System Atlas',
    subtitle: 'Automated multi-step processes, roadmaps, and Grok dispatch',
    icon: GitBranch,
    accentColor: '#38bdf8',
    badge: 'SYSTEM ORCHESTRATION',
    subChoices: [
      {
        id: 'atlas',
        title: 'Master Workflow Atlas',
        tagline: 'Interactive department flow charts and triggers',
        icon: GitBranch,
        color: '#38bdf8',
        badge: 'ARCHITECTURE',
        description: 'Visual flow diagrams showing triggers, decision branching, and backend automations across all desks.',
        primaryLink: { label: 'Launch Atlas', path: '/admin/workflows' },
        links: [
          { label: '🗺️ Master Workflow Atlas Overview', path: '/admin/workflows', highlight: true },
          { label: '📊 Marketing Workflow', path: '/admin/workflows/marketing' },
          { label: '📊 Sales & Recruiting Workflow', path: '/admin/workflows/sales' },
          { label: '📊 DNN Intelligence Workflow', path: '/admin/workflows/dnn' },
        ],
      },
      {
        id: 'roadmap_completion',
        title: 'Road Map to Completion',
        tagline: 'Real-time project milestone and delivery tracking',
        icon: Map,
        color: '#10b981',
        badge: 'MILESTONES',
        description: 'Master show sheet and operational milestone status for all platform capabilities.',
        primaryLink: { label: 'Open Road Map', path: '/admin/roadmap' },
        links: [
          { label: '📍 Road Map to Completion', path: '/admin/roadmap', highlight: true },
          { label: '📋 Master Show Sheet', path: '/admin/show-sheet' },
          { label: '🖥️ Claude Screen Viewer', path: '/admin/claude-screen-viewer' },
        ],
      },
      {
        id: 'dispatch_grok',
        title: 'Dispatch Log & AI Specialists',
        tagline: 'Execution logs, command center, and specialist agents',
        icon: Zap,
        color: '#f59e0b',
        badge: 'AUTOMATION',
        description: 'Monitor real-time task dispatches, specialist worker assignments, and Grok chief orchestration.',
        primaryLink: { label: 'Grok Command', path: '/admin/grok-command' },
        links: [
          { label: '⚡ Grok Command Console', path: '/admin/grok-command', highlight: true },
          { label: '📜 Dispatch Execution Log', path: '/admin/dispatch-log' },
          { label: '🤖 Library Specialists Roster', path: '/admin/library-specialists' },
        ],
      },
    ],
  },
  agents: {
    id: 'agents',
    name: 'Agent Desk & Command Center',
    subtitle: 'Affiliate recruiting, top agent roster, workfiles, and agreements',
    icon: ClipboardList,
    accentColor: '#60a5fa',
    badge: 'NETWORK MANAGEMENT',
    subChoices: [
      {
        id: 'command_center',
        title: 'Agent Command Center',
        tagline: 'Active relocation transactions and agent workfiles',
        icon: ClipboardList,
        color: '#60a5fa',
        badge: 'CLIENT FILES',
        description: 'Manage live client relocation workfiles, milestone progress, and communication threads.',
        primaryLink: { label: 'Open Command Center', path: '/agent-command-center' },
        links: [
          { label: '📋 Agent Command Center', path: '/agent-command-center', highlight: true },
          { label: '⭐ Active Relocation Agents Roster', path: '/admin/active-relocation-agents' },
          { label: '🤝 Referral Agents Network', path: '/admin/referral-agents' },
        ],
      },
      {
        id: 'recruiting_pipeline',
        title: 'Affiliate Recruiting & Outreach',
        tagline: 'Bob Dyson contacts, top agent prospects, and pitches',
        icon: Users,
        color: '#10b981',
        badge: 'RECRUITMENT',
        description: 'Target top-producing independent agents across destination markets to join the PRN network.',
        primaryLink: { label: 'Recruiting Pipeline', path: '/admin/affiliate-recruiting' },
        links: [
          { label: '🎯 Affiliate Recruiting Pipeline', path: '/admin/affiliate-recruiting', highlight: true },
          { label: '👤 Bob Dyson Contact List', path: '/admin/bob-dyson-contacts', highlight: true },
          { label: '📜 Top Relocation Agent Prospects', path: '/admin/roster' },
          { label: '🚀 Exodus Pitch Presentation', path: '/admin/exodus-pitch' },
          { label: '🎁 Partner Benefits Overview', path: '/admin/partner-benefits' },
        ],
      },
      {
        id: 'agreements_compliance',
        title: 'Agreements & Legal Compliance',
        tagline: 'Master agreements, PRN contracts, and fee distribution',
        icon: ShieldCheck,
        color: '#D4AF37',
        badge: 'FIDUCIARY CONTRACTS',
        description: 'Issue 25% referral agreements, verify DRE licensing, and audit executed contractor packages.',
        primaryLink: { label: 'Master Agreement', path: '/admin/master-agreement' },
        links: [
          { label: '📜 Master Referral & Relo Mgmt Agreement', path: '/admin/master-agreement', highlight: true },
          { label: '✍️ PRN Agreements Generator', path: '/admin/prn-agreements' },
          { label: '📥 Agreement Submissions Tracker', path: '/admin/agreement-submissions' },
          { label: '🤝 Lead Handoff Desk', path: '/admin/lead-handoff' },
        ],
      },
    ],
  },
  listing_outreach: {
    id: 'listing_outreach',
    name: 'MLS Listing Agent Outreach',
    subtitle: 'Prospecting, skip tracing, and personalized agent preview delivery',
    icon: MapPin,
    accentColor: '#f59e0b',
    badge: 'DIRECT OUTREACH',
    subChoices: [
      {
        id: 'listing_prospects',
        title: 'Listing Agent CRM & Outreach',
        tagline: 'Track active MLS listings and outreach campaigns',
        icon: MapPin,
        color: '#f59e0b',
        badge: 'MLS PROSPECTING',
        description: 'Contact MLS listing agents with custom fiduciary co-marketing presentations.',
        primaryLink: { label: 'Listing Prospects', path: '/admin/listing-prospects' },
        links: [
          { label: '📍 MLS Listing Agent Outreach Hub', path: '/admin/listing-prospects', highlight: true },
          { label: '🔍 Search Listing Profiles', path: '/admin/search-profiles' },
          { label: '📱 Quick Send (Video / Page → SMS)', path: '/admin/quick-send' },
        ],
      },
      {
        id: 'skip_tracing',
        title: 'Skip Trace & Property Research',
        tagline: 'BatchData property lookups and owner intelligence',
        icon: Fingerprint,
        color: '#3b82f6',
        badge: 'INTELLIGENCE',
        description: 'Find validated phone numbers, emails, and corporate ownership for off-market and MLS listings.',
        primaryLink: { label: 'Skip Trace Lookup', path: '/admin/skip-trace' },
        links: [
          { label: '🔎 Skip Trace Single Lookup', path: '/admin/skip-trace', highlight: true },
          { label: '📦 Bulk Skip Trace CSV Importer', path: '/admin/bulk-skip-trace' },
          { label: '📋 Owner Response Board (Kanban)', path: '/admin/owner-kanban' },
          { label: '🏡 Listing Owners Directory', path: '/admin/owners' },
        ],
      },
      {
        id: 'outreach_pipeline',
        title: 'Outreach Pipeline & SMS Logs',
        tagline: 'SMS campaigns, response queues, and delivery metrics',
        icon: SendHorizontal,
        color: '#10b981',
        badge: 'DELIVERY SYSTEM',
        description: 'Monitor outreach stages, review sent messages, and follow up with interested sellers and agents.',
        primaryLink: { label: 'Outreach Pipeline', path: '/admin/outreach-pipeline' },
        links: [
          { label: '🚀 Outreach Pipeline Stages', path: '/admin/outreach-pipeline', highlight: true },
          { label: '💬 Compose Direct SMS Message', path: '/admin/compose-sms' },
          { label: '📜 Batch SMS Audit Logs', path: '/admin/batch-sms-log' },
          { label: '📊 Outreach Performance Analytics', path: '/admin/outreach-analytics' },
        ],
      },
    ],
  },
  wisdom: {
    id: 'wisdom',
    name: 'Wisdom Relo & Brokerage Suite',
    subtitle: 'Wisdom Properties subscriber hub, escrow auditing, and listings',
    icon: Building2,
    accentColor: '#10b981',
    badge: 'SUBSCRIBER #1',
    subChoices: [
      {
        id: 'escrow_audit',
        title: 'Escrows & Brokermint Doc Audit',
        tagline: 'Escrow tracking, file audits, and compliance checks',
        icon: ShieldCheck,
        color: '#10b981',
        badge: 'BACKOFFICE',
        description: 'Live escrow transaction sync from Brokermint, milestone checklist validation, and AI compliance audit.',
        primaryLink: { label: 'Escrow Management', path: '/admin/wisdom/escrow' },
        links: [
          { label: '🛡️ Escrow Management & Deadlines', path: '/admin/wisdom/escrow', highlight: true },
          { label: '🔍 Transaction Doc Audit (by Escrow #)', path: '/admin/wisdom/audit', highlight: true },
          { label: '📄 AI Compliance Review Uploader', path: '/admin/compliance-review' },
        ],
      },
      {
        id: 'client_records',
        title: 'Listing & Buying Clients',
        tagline: 'Client portfolios, transaction files, and agents',
        icon: Home,
        color: '#3b82f6',
        badge: 'PORTFOLIO',
        description: 'View active listing clients, buying clients, company agents, and broker referrals.',
        primaryLink: { label: 'Listing Clients', path: '/admin/wisdom/listings' },
        links: [
          { label: '🏡 Listing Clients Hub', path: '/admin/wisdom/listings', highlight: true },
          { label: '🛍️ Buying Clients Roster', path: '/admin/wisdom/buying-clients' },
          { label: '👥 Company & Network Agents', path: '/admin/wisdom/agents' },
          { label: '🏢 Brokerage Client Dashboard', path: '/brokerage' },
        ],
      },
      {
        id: 'marketing_presence',
        title: 'Marketing & Luxury Presence',
        tagline: 'Luxury Presence website builder and co-branded campaigns',
        icon: Star,
        color: '#D4AF37',
        badge: 'BRANDING',
        description: 'Manage custom domain branding, luxury presence showcase settings, and co-branded marketing blasts.',
        primaryLink: { label: 'Luxury Presence Builder', path: '/admin/wisdom/luxury' },
        links: [
          { label: '✨ Luxury Presence Website Builder', path: '/admin/wisdom/luxury', highlight: true },
          { label: '📈 Wisdom Marketing Campaigns', path: '/admin/wisdom/marketing' },
          { label: '🤝 Agent Referrals Bureau', path: '/brokerage/referrals' },
        ],
      },
    ],
  },
  marketing: {
    id: 'marketing',
    name: 'Marketing Campaigns & PR Desk',
    subtitle: 'Automated SMS campaigns, video marketing, press kits, and media CRM',
    icon: SendHorizontal,
    accentColor: '#ec4899',
    badge: 'GROWTH ENGINE',
    subChoices: [
      {
        id: 'campaigns_sms',
        title: 'SMS Campaigns & Sequencing',
        tagline: 'Multi-step sequences, scheduled drops, and analytics',
        icon: Calendar,
        color: '#ec4899',
        badge: 'CAMPAIGNS',
        description: 'Automate high-conversion SMS sequences for homeowners, relocating families, and partner agents.',
        primaryLink: { label: 'Campaigns Hub', path: '/admin/marketing-campaigns-hub' },
        links: [
          { label: '🎯 Marketing Campaigns Hub', path: '/admin/marketing-campaigns-hub', highlight: true },
          { label: '📅 Scheduled SMS Campaigns', path: '/admin/scheduled-campaigns' },
          { label: '💬 Multi-Step SMS Sequences', path: '/admin/sms-sequences' },
          { label: '📊 Campaign Performance Metrics', path: '/admin/outreach-analytics' },
        ],
      },
      {
        id: 'video_media',
        title: 'Video Marketing & Vault',
        tagline: 'Video SMS drops, explainer vaults, and decks',
        icon: Video,
        color: '#8b5cf6',
        badge: 'RICH MEDIA',
        description: 'Deploy video SMS messages with Charlie AI explainers and manage presentation slide decks.',
        primaryLink: { label: 'Video SMS Campaigns', path: '/admin/video-sms-campaign' },
        links: [
          { label: '📹 Video SMS Campaigns', path: '/admin/video-sms-campaign', highlight: true },
          { label: '🎬 Media Video Library', path: '/admin/video-library' },
          { label: '📑 Presentation Slide Deck Library', path: '/admin/presentation-library' },
          { label: '🚀 Social Media Launch Desk', path: '/admin/social-launch' },
        ],
      },
      {
        id: 'pr_media_crm',
        title: 'PR & Media Pitching',
        tagline: 'Journalist outreach, press kit assets, and pitches',
        icon: Newspaper,
        color: '#D4AF37',
        badge: 'EARNED MEDIA',
        description: 'Track real estate journalists, customize press releases, and distribute national media pitches.',
        primaryLink: { label: 'Media CRM', path: '/admin/media-crm' },
        links: [
          { label: '📰 Real Estate Media CRM', path: '/admin/media-crm', highlight: true },
          { label: '⭐ Media Pitch Tracker', path: '/admin/pitch-tracker' },
          { label: '📦 Press Kit Digital Assets', path: '/admin/press-kit' },
          { label: '✍️ Mass Pitch Personalizer', path: '/admin/mass-pitch' },
        ],
      },
    ],
  },
  calendar: {
    id: 'calendar',
    name: 'Calendar & Relocation Schedules',
    subtitle: 'Relocation milestones, home tour itineraries, and closing deadlines',
    icon: Calendar,
    accentColor: '#a855f7',
    badge: 'MOVE TIMELINE',
    subChoices: [
      {
        id: 'move_milestones',
        title: 'Interactive Relocation Calendar',
        tagline: 'Track client moving dates and critical milestones',
        icon: Calendar,
        color: '#a855f7',
        badge: 'CLIENT DATES',
        description: 'Interactive monthly and daily schedule of moves, key turnover dates, and van line logistics.',
        primaryLink: { label: 'Open Full Calendar', path: '/calendar' },
        links: [
          { label: '🗓️ Relocation Calendar Mini App', path: '/calendar', highlight: true },
          { label: '📋 Master Client Roadmaps', path: '/client-roadmap' },
          { label: '🏠 Intake Schedule Sequence', path: '/relocation-intake' },
        ],
      },
      {
        id: 'escrow_deadlines',
        title: 'Escrow & Transaction Deadlines',
        tagline: 'Brokermint contingency periods & closing dates',
        icon: ShieldCheck,
        color: '#10b981',
        badge: 'ESCROW SCHEDULE',
        description: 'Monitor loan contingencies, appraisal deadlines, and scheduled close of escrow dates.',
        primaryLink: { label: 'Escrow Deadlines', path: '/admin/wisdom/escrow' },
        links: [
          { label: '🛡️ Escrow Management Deadlines', path: '/admin/wisdom/escrow', highlight: true },
          { label: '🔍 Transaction Document Audits', path: '/admin/wisdom/audit' },
          { label: '📄 AI Compliance Reviews', path: '/admin/compliance-review' },
        ],
      },
      {
        id: 'marketing_calendar',
        title: 'Campaign & Broadcast Schedule',
        tagline: '6AM Morning brief broadcasts & scheduled SMS drops',
        icon: Clock,
        color: '#f59e0b',
        badge: 'AUTOMATED DROPS',
        description: 'View scheduled SMS campaigns, recurring morning brief production, and weekly recap distributions.',
        primaryLink: { label: 'Scheduled Campaigns', path: '/admin/scheduled-campaigns' },
        links: [
          { label: '📅 Scheduled SMS Campaigns', path: '/admin/scheduled-campaigns', highlight: true },
          { label: '🎬 Daily Show Production Pipeline', path: '/admin/dnn/show-pipeline' },
          { label: '🎯 Outreach Campaign Roadmap', path: '/admin/campaign-roadmap' },
        ],
      },
    ],
  },
  email: {
    id: 'email',
    name: 'Email Desk & bob@dysonrelo.com',
    subtitle: 'Sending verification via Resend, Microsoft 365 inbound routing, and client threads',
    icon: Mail,
    accentColor: '#38bdf8',
    badge: 'bob@dysonrelo.com',
    subChoices: [
      {
        id: 'email_live_desk',
        title: 'bob@dysonrelo.com Live Verification',
        tagline: 'Real-time outbound sending & inbound MX routing diagnostics',
        icon: Mail,
        color: '#38bdf8',
        badge: 'VERIFIED SENDING',
        description: 'Inspect Resend DKIM/SPF domain verification, Microsoft 365 inbound MX destination, and run one-click test sends.',
        primaryLink: { label: 'Email Mini App', path: '/email' },
        links: [
          { label: '✉️ Email Client Mini App', path: '/email', highlight: true },
          { label: '📤 Quick Send (Video / Page → Email)', path: '/admin/quick-send' },
          { label: '📨 Communications Hub', path: '/admin/dnn/communications' },
        ],
      },
      {
        id: 'client_comms',
        title: 'Client Communications Desk',
        tagline: 'Message history, lead replies, and inquiry threads',
        icon: MessageCircle,
        color: '#10b981',
        badge: 'CLIENT LOGS',
        description: 'Review communications with relocation buyers, listing agents, and vetting candidates.',
        primaryLink: { label: 'Communications Logs', path: '/admin/communications' },
        links: [
          { label: '💬 Admin Communications Roster', path: '/admin/communications', highlight: true },
          { label: '🚩 Flagged Conversations', path: '/admin/flagged-conversations' },
          { label: '👥 Subscriber CRM Directory', path: '/admin/dnn/subscribers' },
        ],
      },
      {
        id: 'email_outreach',
        title: 'B2B & Subscriber Email Blasts',
        tagline: 'Resend high-volume multi-inbox rotation & newsletters',
        icon: Send,
        color: '#D4AF37',
        badge: 'RESEND BLAST',
        description: 'Multi-inbox agent outreach with 40/day cap, morning broadcast email notifications, and invite dispatches.',
        primaryLink: { label: 'Subscriber Invites', path: '/admin/subscriber-invite' },
        links: [
          { label: '✉️ Send Subscriber Invites', path: '/admin/subscriber-invite', highlight: true },
          { label: '📍 MLS Listing Agent Outreach Hub', path: '/admin/listing-prospects' },
          { label: '📰 8AM Morning Email Blast Workflow', path: '/admin/workflows/dnn' },
        ],
      },
    ],
  },
  text: {
    id: 'text',
    name: 'Text / SMS Communications Desk',
    subtitle: 'Twilio active carrier line, automated 10DLC pipelines, and client SMS alerts',
    icon: MessageSquare,
    accentColor: '#10b981',
    badge: 'TWILIO ACTIVE',
    subChoices: [
      {
        id: 'direct_sms',
        title: 'Compose & Direct SMS',
        tagline: 'Send individual and targeted messages to owners & clients',
        icon: SendHorizontal,
        color: '#10b981',
        badge: 'CARRIER LINE',
        description: 'Send direct text messages to homeowners, follow up with leads, and receive automatic email alerts on replies.',
        primaryLink: { label: 'Compose SMS', path: '/admin/compose-sms' },
        links: [
          { label: '💬 Compose Single SMS', path: '/admin/compose-sms', highlight: true },
          { label: '📱 Quick Send Video / Page via SMS', path: '/admin/quick-send' },
          { label: '📞 Direct Call / Text: (858) 353-1200', path: '/admin/outreach-pipeline' },
        ],
      },
      {
        id: 'outreach_pipeline_sms',
        title: 'Outreach Pipeline & Response Board',
        tagline: 'Owner response Kanban & lead qualification workflow',
        icon: Users,
        color: '#f59e0b',
        badge: 'RESPONSES',
        description: 'Track inbound text responses from homeowners, qualify relocation intent, and assign vetted agents.',
        primaryLink: { label: 'Outreach Pipeline', path: '/admin/outreach-pipeline' },
        links: [
          { label: '🚀 Outreach Pipeline Stages', path: '/admin/outreach-pipeline', highlight: true },
          { label: '📋 Owner Response Kanban', path: '/admin/owner-kanban' },
          { label: '🏡 Listing Owners Directory', path: '/admin/owners' },
        ],
      },
      {
        id: 'batch_logs',
        title: 'Batch SMS Logs & Sequences',
        tagline: 'Audit trail of dispatched SMS campaigns & automated drips',
        icon: List,
        color: '#ec4899',
        badge: 'AUDIT LOGS',
        description: 'Real-time delivery verification, failure tracking, opt-out management, and multi-step SMS sequences.',
        primaryLink: { label: 'Batch SMS Logs', path: '/admin/batch-sms-log' },
        links: [
          { label: '📜 Batch SMS Audit Logs', path: '/admin/batch-sms-log', highlight: true },
          { label: '💬 Multi-Step SMS Sequences', path: '/admin/sms-sequences' },
          { label: '📊 Outreach Analytics Dashboard', path: '/admin/outreach-analytics' },
        ],
      },
    ],
  },
  calculator: {
    id: 'calculator',
    name: 'Mortgage & Relocation Calculator',
    subtitle: 'Principal & interest, property taxes, van line moving costs, and temporary lodging',
    icon: Calculator,
    accentColor: '#34d399',
    badge: 'MORTGAGE & RELO',
    subChoices: [
      {
        id: 'mortgage_calc',
        title: 'Mortgage & Payment Estimator',
        tagline: 'Home price, down payment %, interest rate & taxes',
        icon: Calculator,
        color: '#34d399',
        badge: 'P&I + TAXES',
        description: 'Accurate monthly mortgage calculation including P&I, state-specific property taxes, and hazard insurance.',
        primaryLink: { label: 'Open Calculator', path: '/calculator' },
        links: [
          { label: '🧮 Mortgage & Payment Tool', path: '/calculator', highlight: true },
          { label: '💳 Financial Services Hub', path: '/financial-services' },
          { label: '🏦 Select a Vetted Lender', path: '/admin/dnn/lender-vetting' },
        ],
      },
      {
        id: 'moving_costs',
        title: 'Van Line & Relocation Logistics',
        tagline: 'Distance, bedrooms, packing & storage estimation',
        icon: Compass,
        color: '#f59e0b',
        badge: 'MOVING ESTIMATE',
        description: 'Calculate comprehensive interstate moving costs, storage units, mileage allowances, and transition budgets.',
        primaryLink: { label: 'Relo Estimator', path: '/calculator' },
        links: [
          { label: '🚚 Relocation Expense Estimator', path: '/calculator', highlight: true },
          { label: '📋 Master Client Roadmaps', path: '/client-roadmap' },
          { label: '🏡 Relocation Intake Planner', path: '/relocation-intake' },
        ],
      },
      {
        id: 'tax_savings',
        title: 'State Tax Differential & Net Sheet',
        tagline: 'California vs Texas/Florida/Nevada tax comparisons',
        icon: Sparkles,
        color: '#D4AF37',
        badge: 'TAX BATTLEPLAN',
        description: 'Model real cash-flow advantages of moving between state tax brackets, capital gains timing, and 1031 exchanges.',
        primaryLink: { label: 'Tax & Solutions Map', path: '/solutions' },
        links: [
          { label: '✨ Tax & Relo Solutions Map', path: '/solutions', highlight: true },
          { label: '⚖️ Fiduciary Transparency Deck', path: '/transparency' },
          { label: '📊 Market Data Hub', path: '/admin/dnn/market-data' },
        ],
      },
    ],
  },
  weather: {
    id: 'weather',
    name: 'Destination Climates & Weather Hub',
    subtitle: 'Seasonal temperatures, annual sunny days, and live 5-day forecasts for top relocation destinations',
    icon: CloudSun,
    accentColor: '#38bdf8',
    badge: 'CLIMATE RADAR',
    subChoices: [
      {
        id: 'destination_forecasts',
        title: 'Top Relocation Market Forecasts',
        tagline: 'Scottsdale, Austin, Nashville, Miami & Incline Village',
        icon: CloudSun,
        color: '#38bdf8',
        badge: '5-DAY WEATHER',
        description: 'Live weather updates, seasonal temperatures, humidity indexes, and conditions in top relocation cities.',
        primaryLink: { label: 'Open Weather Hub', path: '/weather' },
        links: [
          { label: '☀️ Weather & Climate Mini App', path: '/weather', highlight: true },
          { label: '🗺️ Explore Destination Strip', path: '/city-guide' },
          { label: '🌆 City Relocation Guides', path: '/city-guide' },
        ],
      },
      {
        id: 'climate_comparison',
        title: 'Climate vs California Benchmark',
        tagline: 'Compare winter lows, annual sun days, and summer humidity',
        icon: Thermometer,
        color: '#f59e0b',
        badge: 'BENCHMARK',
        description: 'Side-by-side analysis comparing California coastal weather with destination mountain, desert, and sun-belt climates.',
        primaryLink: { label: 'Compare Climates', path: '/weather' },
        links: [
          { label: '🌡️ Climate Comparison Tool', path: '/weather', highlight: true },
          { label: '📍 Vetted Agents by City', path: '/find-agent' },
          { label: '📰 DNN Market Data Feed', path: '/admin/dnn/market-data' },
        ],
      },
      {
        id: 'lifestyle_matching',
        title: 'Weather & Tax Matchmaker',
        tagline: 'Match buyers to ideal climate and 0% tax states',
        icon: Sparkles,
        color: '#10b981',
        badge: 'MATCHMAKER',
        description: 'Synthesize optimal lifestyle factors: 300+ days of sun, low tax jurisdiction, and luxury real estate availability.',
        primaryLink: { label: 'Relo Solutions Map', path: '/solutions' },
        links: [
          { label: '🌟 Lifestyle & Tax Solutions', path: '/solutions', highlight: true },
          { label: '🏡 Search Listing Profiles', path: '/admin/search-profiles' },
          { label: '💬 Talk with Charlie AI', path: '/talking-app' },
        ],
      },
    ],
  },
  charlie: {
    id: 'charlie',
    name: "Charlie Simmons AI Concierge Desk",
    subtitle: 'Real-time conversational voice mode (V2V), trained knowledge base Q&A, and spoken script studio',
    icon: Mic,
    accentColor: '#e8c84a',
    badge: 'VOICE-TO-VOICE',
    subChoices: [
      {
        id: 'v2v_voice',
        title: 'Voice-to-Voice (V2V) Concierge',
        tagline: 'Real-time two-way spoken conversation with Gemini Live',
        icon: Mic,
        color: '#10b981',
        badge: 'LIVE AUDIO',
        description: 'Experience hands-free voice interaction. Charlie speaks in an authentic broadcast tone, answering relocation queries instantly.',
        primaryLink: { label: 'Launch Voice Studio', path: '/talking-app' },
        links: [
          { label: '🎙️ Spoken Voice Studio (Talking App)', path: '/talking-app', highlight: true },
          { label: '📊 Voice Concierge Analytics', path: '/admin/voice-concierge-analytics' },
          { label: '🗣️ Charlie Voice Presentation', path: '/charlie-voice' },
        ],
      },
      {
        id: 'knowledge_brain',
        title: 'Charlie Knowledge Base & Q&A Brain',
        tagline: 'Vetting criteria, process knowledge, and escalation handling',
        icon: Brain,
        color: '#a855f7',
        badge: 'TRAINED BRAIN',
        description: 'Manage Charlie’s trained facts, vetted partner standards, relocation processes, and consumer answers.',
        primaryLink: { label: 'Knowledge Base', path: '/admin/charlie-knowledge-base' },
        links: [
          { label: '🧠 Charlie Knowledge Base Roster', path: '/admin/charlie-knowledge-base', highlight: true },
          { label: '⚠️ Review Flagged Escalations', path: '/admin/charlie-escalations' },
          { label: '🎥 Bob Dyson Video Answers Library', path: '/admin/bob-library' },
        ],
      },
      {
        id: 'broadcast_scripts',
        title: 'Spoken Scripts & HeyGen Pipeline',
        tagline: 'Daily 6AM broadcast scripts, audio synthesis, and avatars',
        icon: ScrollText,
        color: '#D4AF37',
        badge: 'SCRIPT STUDIO',
        description: 'Audit and edit AI-generated morning brief scripts, verify Ruben American voice synthesis, and test HeyGen renders.',
        primaryLink: { label: 'Charlie Scripts', path: '/admin/charlie-scripts' },
        links: [
          { label: '📜 Charlie Spoken Scripts Roster', path: '/admin/charlie-scripts', highlight: true },
          { label: '🎬 DNN Script Review Desk', path: '/admin/dnn/script-review' },
          { label: '⚡ Pipeline Credit Monitor', path: '/admin/heygen-credits' },
        ],
      },
    ],
  },
  specialists: {
    id: 'specialists',
    name: 'AI Library Specialists Desk',
    subtitle: 'Autonomous agents, Canon & Playbook specifications, and specialist conduit',
    icon: Brain,
    accentColor: '#c084fc',
    badge: 'LIBRARY SPECIALISTS',
    subChoices: [
      {
        id: 'specialist_roster',
        title: 'Specialists Roster & Canon',
        tagline: 'Autonomous AI roles and domain authority definitions',
        icon: Brain,
        color: '#c084fc',
        badge: 'AI ROLES',
        description: 'Manage specialist personas, prompt templates, tool permissions, and core domain instructions.',
        primaryLink: { label: 'Specialists Roster', path: '/admin/library-specialists' },
        links: [
          { label: '📜 AI Library Specialists Console', path: '/admin/library-specialists', highlight: true },
          { label: '🗺️ Master Workflow Atlas', path: '/admin/workflows' },
          { label: '⚡ Grok Command Console', path: '/admin/grok-command' },
        ],
      },
      {
        id: 'specialist_conduit',
        title: 'Specialist Conduit & Dispatches',
        tagline: 'Real-time agent execution and task handoffs',
        icon: Zap,
        color: '#f59e0b',
        badge: 'CONDUIT',
        description: 'Track background tasks dispatched to autonomous specialists and inspect live execution outputs.',
        primaryLink: { label: 'Dispatch Log', path: '/admin/dispatch-log' },
        links: [
          { label: '📜 Dispatch Execution Log', path: '/admin/dispatch-log', highlight: true },
          { label: '📍 Road Map to Completion', path: '/admin/roadmap' },
          { label: '📋 Master Show Sheet', path: '/admin/show-sheet' },
        ],
      },
      {
        id: 'specialist_connect',
        title: 'Assistant Connect & Integrations',
        tagline: 'MCP server endpoints and external AI bridge',
        icon: Plug,
        color: '#10b981',
        badge: 'INTEGRATIONS',
        description: 'Expose live app endpoints to Claude Desktop, ChatGPT, and external autonomous LLM agents.',
        primaryLink: { label: 'Connect Assistant', path: '/connect' },
        links: [
          { label: '🔌 Connect AI Assistant', path: '/connect', highlight: true },
          { label: '👁️ Grok Screen Viewer', path: '/admin/claude-screen-viewer' },
          { label: '💬 Spoken Voice Studio', path: '/talking-app' },
        ],
      },
    ],
  },
  grok_viewer: {
    id: 'grok_viewer',
    name: 'Grok Screen Viewer & Vision',
    subtitle: 'Real-time UI screen analysis, visual audit logs, and command control',
    icon: Monitor,
    accentColor: '#38bdf8',
    badge: 'SCREEN VISION',
    subChoices: [
      {
        id: 'screen_viewer',
        title: 'Grok Screen Vision Console',
        tagline: 'Multimodal UI inspection and live page audits',
        icon: Monitor,
        color: '#38bdf8',
        badge: 'VISION AI',
        description: 'Inspect live page screenshots, detect UI layout inconsistencies, and capture design feedback.',
        primaryLink: { label: 'Screen Viewer', path: '/admin/claude-screen-viewer' },
        links: [
          { label: '👁️ Grok Screen Viewer Console', path: '/admin/claude-screen-viewer', highlight: true },
          { label: '⚡ Grok Command Console', path: '/admin/grok-command' },
          { label: '📜 Dispatch Execution Log', path: '/admin/dispatch-log' },
        ],
      },
      {
        id: 'grok_orchestrator',
        title: 'Grok Chief Orchestration',
        tagline: 'Autonomous task delegation and system audits',
        icon: Zap,
        color: '#f59e0b',
        badge: 'COMMAND',
        description: 'Send high-level orchestration directives to Grok across marketing, sales, and DNN pipelines.',
        primaryLink: { label: 'Grok Command', path: '/admin/grok-command' },
        links: [
          { label: '⚡ Grok Command Console', path: '/admin/grok-command', highlight: true },
          { label: '🤖 Library Specialists Roster', path: '/admin/library-specialists' },
          { label: '🗺️ Master Workflow Atlas', path: '/admin/workflows' },
        ],
      },
      {
        id: 'visual_pipeline',
        title: 'Visual Assets & Front Door Lab',
        tagline: 'Verified studio renders and luxury front door lab',
        icon: Sparkles,
        color: '#D4AF37',
        badge: 'LABS',
        description: 'Inspect the verified 16:9 studio desk layout and luxury presence showcase experiments.',
        primaryLink: { label: 'Front Door Lab', path: '/admin/front-door-lab' },
        links: [
          { label: '✨ Front Door Lab Showcase', path: '/admin/front-door-lab', highlight: true },
          { label: '📦 Archived Studio Landing', path: '/admin/archived/studio-landing' },
          { label: '🎬 Video Preview & Blast', path: '/admin/dnn/video-preview' },
        ],
      },
    ],
  },
  connect_ai: {
    id: 'connect_ai',
    name: 'Connect AI Assistant & MCP',
    subtitle: 'Third-party agent bridging, MCP servers, and custom AI integrations',
    icon: Plug,
    accentColor: '#fbbf24',
    badge: 'EXTERNAL BRIDGE',
    subChoices: [
      {
        id: 'assistant_bridge',
        title: 'Connect AI Assistant Hub',
        tagline: 'Claude Desktop, ChatGPT & Cursor integration',
        icon: Plug,
        color: '#fbbf24',
        badge: 'APP MCP',
        description: 'Configure secure bearer tokens and endpoints for external AI clients to access DysonRelo tools.',
        primaryLink: { label: 'Connect Assistant', path: '/connect' },
        links: [
          { label: '🔌 Connect AI Assistant', path: '/connect', highlight: true },
          { label: '🤖 Library Specialists Roster', path: '/admin/library-specialists' },
          { label: '🗺️ Master Workflow Atlas', path: '/admin/workflows' },
        ],
      },
      {
        id: 'charlie_voice_link',
        title: 'Charlie Voice & Chat Integrations',
        tagline: 'Real-time Gemini Live session connection and audio',
        icon: Mic,
        color: '#10b981',
        badge: 'V2V VOICE',
        description: 'Manage bidirectional voice streaming configurations, microphone policies, and mobile audio.',
        primaryLink: { label: 'Voice Studio', path: '/talking-app' },
        links: [
          { label: '🎙️ Spoken Voice Studio (Talking App)', path: '/talking-app', highlight: true },
          { label: '📊 Voice Concierge Analytics', path: '/admin/voice-concierge-analytics' },
          { label: '💬 Client Live Chat', path: '/chat' },
        ],
      },
      {
        id: 'system_webhooks',
        title: 'Twilio & Email Webhook Health',
        tagline: 'Carrier lines, inbound routing, and Resend status',
        icon: Mail,
        color: '#38bdf8',
        badge: 'LIVE HEALTH',
        description: 'Audit live email MX records, Resend domain verification, and Twilio 10DLC inbound message webhooks.',
        primaryLink: { label: 'Email Desk', path: '/email' },
        links: [
          { label: '✉️ Email Desk Diagnostics', path: '/email', highlight: true },
          { label: '💬 Direct SMS Compose', path: '/admin/compose-sms' },
          { label: '📜 Batch SMS Logs', path: '/admin/batch-sms-log' },
        ],
      },
    ],
  },
  marketing_hub: {
    id: 'marketing_hub',
    name: 'Marketing Campaigns Hub',
    subtitle: 'Central command for SMS blasts, video drops, sequences, and analytics',
    icon: Megaphone,
    accentColor: '#ec4899',
    badge: 'CAMPAIGNS HUB',
    subChoices: [
      {
        id: 'campaigns_central',
        title: 'Marketing Campaigns Central',
        tagline: 'Active campaigns, multi-stage drips & scheduled drops',
        icon: Megaphone,
        color: '#ec4899',
        badge: 'DISPATCH',
        description: 'Review and trigger high-conversion outreach drops across target cities and relocation lists.',
        primaryLink: { label: 'Campaigns Hub', path: '/admin/marketing-campaigns-hub' },
        links: [
          { label: '🎯 Marketing Campaigns Hub', path: '/admin/marketing-campaigns-hub', highlight: true },
          { label: '📅 Scheduled SMS Campaigns', path: '/admin/scheduled-campaigns' },
          { label: '💬 Multi-Step SMS Sequences', path: '/admin/sms-sequences' },
        ],
      },
      {
        id: 'quick_actions',
        title: 'Quick Send & Instant Delivery',
        tagline: 'Directly dispatch any page or video to SMS or email',
        icon: SendHorizontal,
        color: '#10b981',
        badge: 'QUICK SEND',
        description: 'One-click delivery tool to send personalized previews, videos, or agreements to clients and agents.',
        primaryLink: { label: 'Quick Send Tool', path: '/admin/quick-send' },
        links: [
          { label: '📤 Quick Send (Page/Video → SMS/Email)', path: '/admin/quick-send', highlight: true },
          { label: '📹 Video SMS Campaign Builder', path: '/admin/video-sms-campaign' },
          { label: '🎬 Media Video Library', path: '/admin/video-library' },
        ],
      },
      {
        id: 'outreach_analytics',
        title: 'Campaign Analytics & Response Kanban',
        tagline: 'Delivery rates, opt-outs, and lead qualification',
        icon: BarChart3,
        color: '#f59e0b',
        badge: 'METRICS',
        description: 'Track reply rates, conversion funnel progress, and qualify incoming homeowner leads.',
        primaryLink: { label: 'Campaign Analytics', path: '/admin/outreach-analytics' },
        links: [
          { label: '📊 Campaign Performance Analytics', path: '/admin/outreach-analytics', highlight: true },
          { label: '📋 Owner Response Kanban', path: '/admin/owner-kanban' },
          { label: '📜 Batch SMS Audit Logs', path: '/admin/batch-sms-log' },
        ],
      },
    ],
  },
  business_plan: {
    id: 'business_plan',
    name: 'Business Plan & Executive Strategy',
    subtitle: 'Unit economics, SaaS subscriber tiers, and platform roadmaps',
    icon: FileText,
    accentColor: '#D4AF37',
    badge: 'EXECUTIVE SUITE',
    subChoices: [
      {
        id: 'plan_document',
        title: 'Interactive Business Plan',
        tagline: 'Strategic plan, unit economics, and subscriber pricing',
        icon: FileText,
        color: '#D4AF37',
        badge: 'STRATEGY',
        description: 'Explore the DysonRelo business model, referral fee economics, and multi-tenant SaaS architecture.',
        primaryLink: { label: 'Business Plan', path: '/admin/business-plan' },
        links: [
          { label: '📋 Interactive Business Plan', path: '/admin/business-plan', highlight: true },
          { label: '📍 Road Map to Completion', path: '/admin/roadmap' },
          { label: '📋 Master Show Sheet', path: '/admin/show-sheet' },
        ],
      },
      {
        id: 'subscribers_model',
        title: 'Subscribers & Portal Invitations',
        tagline: 'Manage broker, agent, and client subscriptions',
        icon: Users,
        color: '#34d399',
        badge: 'SUBSCRIBERS',
        description: 'Send co-branded portal invites and onboard brokerages to the multi-tenant relocation platform.',
        primaryLink: { label: 'Send Invite', path: '/admin/subscriber-invite' },
        links: [
          { label: '✉️ Send Subscriber Invites', path: '/admin/subscriber-invite', highlight: true },
          { label: '👤 Add Subscriber to Any Portal', path: '/admin/add-subscriber' },
          { label: '👥 Subscriber CRM Directory', path: '/admin/dnn/subscribers' },
        ],
      },
      {
        id: 'financial_metrics',
        title: 'Revenue Projections & Legal Core',
        tagline: 'Referral fee splits and master contracts',
        icon: DollarSign,
        color: '#f59e0b',
        badge: 'REVENUE',
        description: 'Review 25% referral economics, escrow compliance, and executed master contractor agreements.',
        primaryLink: { label: 'Master Agreement', path: '/admin/master-agreement' },
        links: [
          { label: '📜 Master Referral & Relo Mgmt Agreement', path: '/admin/master-agreement', highlight: true },
          { label: '📈 Featured Agent Revenue', path: '/admin/dnn/revenue' },
          { label: '🛡️ Escrow Management Hub', path: '/admin/wisdom/escrow' },
        ],
      },
    ],
  },
  admin_dashboard: {
    id: 'admin_dashboard',
    name: 'Admin Command Console',
    subtitle: 'Executive dashboard, real-time charts, quick tools, and system health',
    icon: LayoutDashboard,
    accentColor: '#e8c84a',
    badge: 'COMMAND CONSOLE',
    subChoices: [
      {
        id: 'console_overview',
        title: 'Live Metrics & System Charts',
        tagline: 'Active clients, listings, and referrals trendline',
        icon: BarChart3,
        color: '#e8c84a',
        badge: 'REAL-TIME',
        description: 'Inspect live charts of active listings by status, incoming referral trends, and pending items.',
        primaryLink: { label: 'Live Metrics', path: '/admin?view=overview' },
        links: [
          { label: '📊 Live Metrics & Chart Overview', path: '/admin?view=overview', highlight: true },
          { label: '🗺️ Master Workflow Atlas', path: '/admin/workflows' },
          { label: '📱 10 Platform Apps Specs', path: '/admin/app-store-mockup' },
        ],
      },
      {
        id: 'quick_tools',
        title: 'Quick Searches & Skip Tracing',
        tagline: 'Instant property lookups and owner contact info',
        icon: Search,
        color: '#3b82f6',
        badge: 'RESEARCH',
        description: 'Find verified owner contact information and manage active MLS property search profiles.',
        primaryLink: { label: 'Skip Trace', path: '/admin/skip-trace' },
        links: [
          { label: '🔎 Skip Trace Single Lookup', path: '/admin/skip-trace', highlight: true },
          { label: '🔍 Search Listing Profiles', path: '/admin/search-profiles' },
          { label: '📋 MLS Listing Agent Outreach Hub', path: '/admin/listing-prospects' },
        ],
      },
      {
        id: 'leads_agreements',
        title: 'Referral Leads & Master Contracts',
        tagline: 'Incoming referral review and contract dispatch',
        icon: ShieldCheck,
        color: '#10b981',
        badge: 'CONTRACTS',
        description: 'Accept or decline submitted referral leads and audit executed independent contractor agreements.',
        primaryLink: { label: 'Referral Leads', path: '/admin/referral-leads' },
        links: [
          { label: '🤝 Referral Leads Desk', path: '/admin/referral-leads', highlight: true },
          { label: '📜 Master Referral Agreement', path: '/admin/master-agreement' },
          { label: '📥 Agreement Submissions Tracker', path: '/admin/agreement-submissions' },
        ],
      },
    ],
  },
  corporate_relo: {
    id: 'corporate_relo',
    name: 'Corporate Relo / HR Desk',
    subtitle: 'B2B executive relocation management, employee guides, and Q&A explainers',
    icon: Building2,
    accentColor: '#60a5fa',
    badge: 'B2B RELO',
    subChoices: [
      {
        id: 'hr_guidelines',
        title: 'HR Guidelines & Explainer Videos',
        tagline: 'Fiduciary corporate move assistance and video sets',
        icon: Video,
        color: '#60a5fa',
        badge: 'EXPLAINERS',
        description: 'Provide HR managers with structured video explanations of policy, reimbursement, and housing assistance.',
        primaryLink: { label: 'Corporate Relo', path: '/admin/corporate-relo' },
        links: [
          { label: '🏢 Corporate Relo Guidelines & Videos', path: '/admin/corporate-relo', highlight: true },
          { label: '🌐 Public Corporate Relo Portal', path: '/corporate-relo' },
          { label: '🎬 Q&A Script Studio', path: '/admin/qa-script-studio' },
        ],
      },
      {
        id: 'b2b_distribution',
        title: 'B2B Audience Distribution',
        tagline: 'Segmented corporate HR campaigns and outbound materials',
        icon: Send,
        color: '#10b981',
        badge: 'DISTRIBUTION',
        description: 'Deliver targeted corporate relocation information packs to corporate HR heads and executives.',
        primaryLink: { label: 'B2B Distribution', path: '/admin/audience-distribution' },
        links: [
          { label: '📤 B2B Audience Distribution Desk', path: '/admin/audience-distribution', highlight: true },
          { label: '🎯 Target Audiences Hub', path: '/admin/target-audiences' },
          { label: '👥 Subscriber CRM', path: '/admin/dnn/subscribers' },
        ],
      },
      {
        id: 'relocation_roadmaps',
        title: 'Employee Move Roadmaps',
        tagline: 'Milestone tracking from home sale to final unpack',
        icon: Map,
        color: '#D4AF37',
        badge: 'ROADMAPS',
        description: 'Track employee relocation tasks with real-time updates and direct concierge oversight.',
        primaryLink: { label: 'Client Roadmap', path: '/client-roadmap' },
        links: [
          { label: '📋 Master Client Roadmaps', path: '/client-roadmap', highlight: true },
          { label: '🏠 Relocation Intake Sequence', path: '/relocation-intake' },
          { label: '⚖️ Fiduciary Transparency Deck', path: '/transparency' },
        ],
      },
    ],
  },
  operations: {
    id: 'operations',
    name: 'Operations & Compliance Desk',
    subtitle: 'Compliance doc review, presentation decks, and transaction operations',
    icon: ShieldCheck,
    accentColor: '#10b981',
    badge: 'OPERATIONS',
    subChoices: [
      {
        id: 'compliance_hub',
        title: 'AI Compliance Doc Review',
        tagline: 'Automated escrow and listing file audit check',
        icon: ShieldCheck,
        color: '#10b981',
        badge: 'AUDIT',
        description: 'Upload and audit transaction files, disclosure packages, and escrow instructions against state guidelines.',
        primaryLink: { label: 'Compliance Review', path: '/admin/compliance-review' },
        links: [
          { label: '🛡️ AI Compliance Document Review', path: '/admin/compliance-review', highlight: true },
          { label: '🔍 Transaction Doc Audit by Escrow #', path: '/admin/wisdom/audit' },
          { label: '🛡️ Escrow Management Desk', path: '/admin/wisdom/escrow' },
        ],
      },
      {
        id: 'presentations_hub',
        title: 'Presentation & Deck Library',
        tagline: 'Slide decks, client presentations, and guides',
        icon: FileText,
        color: '#3b82f6',
        badge: 'DECKS',
        description: 'Access curated client decks, broker partnership presentations, and relocation roadmaps.',
        primaryLink: { label: 'Presentation Library', path: '/admin/presentation-library' },
        links: [
          { label: '📑 Presentation Slide Deck Library', path: '/admin/presentation-library', highlight: true },
          { label: '🚀 Exodus Pitch Presentation', path: '/admin/exodus-pitch' },
          { label: '🎁 Partner Benefits Overview', path: '/admin/partner-benefits' },
        ],
      },
      {
        id: 'qa_studio_desk',
        title: 'Q&A Script Studio',
        tagline: 'Charlie & Bob interview scripts and question sets',
        icon: Video,
        color: '#D4AF37',
        badge: 'Q&A STUDIO',
        description: 'Review and craft conversational Q&A clips addressing the most complex relocation hurdles.',
        primaryLink: { label: 'Q&A Studio', path: '/admin/qa-script-studio' },
        links: [
          { label: '🎬 Q&A Script Studio', path: '/admin/qa-script-studio', highlight: true },
          { label: '🚩 Flagged Conversations', path: '/admin/flagged-conversations' },
          { label: '🤝 Referral Management', path: '/admin/referrals' },
        ],
      },
    ],
  },
  pr_media: {
    id: 'pr_media',
    name: 'PR & Media Relations Desk',
    subtitle: 'Journalist CRM, pitch tracker, press kits, and mass personalization',
    icon: Newspaper,
    accentColor: '#f97316',
    badge: 'EARNED MEDIA',
    subChoices: [
      {
        id: 'media_crm',
        title: 'Real Estate Media CRM',
        tagline: 'Journalist contacts, publication beats, and notes',
        icon: Users,
        color: '#f97316',
        badge: 'CONTACTS',
        description: 'Maintain relationships with national and local real estate journalists covering tax and relocation migration.',
        primaryLink: { label: 'Media CRM', path: '/admin/media-crm' },
        links: [
          { label: '📰 Real Estate Media CRM', path: '/admin/media-crm', highlight: true },
          { label: '⭐ Media Pitch Tracker', path: '/admin/pitch-tracker' },
          { label: '✍️ Mass Pitch Personalizer', path: '/admin/mass-pitch' },
        ],
      },
      {
        id: 'press_kit_assets',
        title: 'Digital Press Kit & Assets',
        tagline: 'Logos, founder bios, headshots, and media kit',
        icon: Package,
        color: '#D4AF37',
        badge: 'PRESS KIT',
        description: 'Download verified high-res logos, official executive bios, headshots, and company backgrounders.',
        primaryLink: { label: 'Press Kit', path: '/admin/press-kit' },
        links: [
          { label: '📦 Press Kit Digital Assets', path: '/admin/press-kit', highlight: true },
          { label: '🌐 Public Media Room', path: '/media' },
          { label: '🚀 Social Media Launch Desk', path: '/admin/social-launch' },
        ],
      },
      {
        id: 'pitch_strategy',
        title: 'Story Pitches & Market Wire',
        tagline: 'Custom pitch angles based on current market trends',
        icon: Megaphone,
        color: '#10b981',
        badge: 'PITCHES',
        description: 'Deliver timely data hooks regarding mortgage rates, exodus states, and buyer incentives to editors.',
        primaryLink: { label: 'Pitch Tracker', path: '/admin/pitch-tracker' },
        links: [
          { label: '⭐ Media Pitch Tracker', path: '/admin/pitch-tracker', highlight: true },
          { label: '📊 Market Data Hub', path: '/admin/dnn/market-data' },
          { label: '📰 DNN News Staging Feed', path: '/admin/dnn/news-feed' },
        ],
      },
    ],
  },
  affiliate_recruiting: {
    id: 'affiliate_recruiting',
    name: 'Affiliate Recruiting Desk',
    subtitle: 'Top-producing agent roster, Bob Dyson contacts, and partnership pitches',
    icon: Users,
    accentColor: '#34d399',
    badge: 'RECRUITMENT',
    subChoices: [
      {
        id: 'recruiting_funnel',
        title: 'Affiliate Recruiting Pipeline',
        tagline: 'Top agent outreach stages, follow-ups & invites',
        icon: Users,
        color: '#34d399',
        badge: 'PIPELINE',
        description: 'Track independent luxury agents across destination markets from initial contact to active PRN affiliate.',
        primaryLink: { label: 'Recruiting Pipeline', path: '/admin/affiliate-recruiting' },
        links: [
          { label: '🎯 Affiliate Recruiting Pipeline', path: '/admin/affiliate-recruiting', highlight: true },
          { label: '👤 Bob Dyson Contact List', path: '/admin/bob-dyson-contacts', highlight: true },
          { label: '📜 Top Relocation Agent Prospects', path: '/admin/roster' },
        ],
      },
      {
        id: 'partnership_decks',
        title: 'Exodus Pitch & Partner Benefits',
        tagline: 'Presentations outlining the 25% referral network model',
        icon: Sparkles,
        color: '#D4AF37',
        badge: 'PRESENTATIONS',
        description: 'Showcase how top agents receive vetted buyer referrals without upfront portal advertising fees.',
        primaryLink: { label: 'Exodus Pitch', path: '/admin/exodus-pitch' },
        links: [
          { label: '🚀 Exodus Pitch Presentation', path: '/admin/exodus-pitch', highlight: true },
          { label: '🎁 Partner Benefits Overview', path: '/admin/partner-benefits' },
          { label: '🌐 Public Agent Subscribe Page', path: '/agent-subscribe' },
        ],
      },
      {
        id: 'prn_roster',
        title: 'Active Network Agents & Referrals',
        tagline: 'Full-time relocation agents and referral-only partners',
        icon: ShieldCheck,
        color: '#3b82f6',
        badge: 'ROSTER',
        description: 'Manage active affiliate agents, verify state licensing status, and track outbound referral assignments.',
        primaryLink: { label: 'Active Agents', path: '/admin/active-relocation-agents' },
        links: [
          { label: '⭐ Active Relocation Agents (Full-Time)', path: '/admin/active-relocation-agents', highlight: true },
          { label: '🤝 Referral Agents (Refer-Only)', path: '/admin/referral-agents' },
          { label: '⚖️ PRN Fee Agreements', path: '/admin/prn-agreements' },
        ],
      },
    ],
  },
  vetting: {
    id: 'vetting',
    name: 'Agent & Lender Vetting Desk',
    subtitle: 'Fiduciary vetting criteria, lender qualification, and PRN agreements',
    icon: Shield,
    accentColor: '#a855f7',
    badge: 'VETTING STANDARDS',
    subChoices: [
      {
        id: 'agent_vetting_standards',
        title: 'Agent Vetting Process',
        tagline: 'Track record, fiduciary ethics, and market expertise',
        icon: Shield,
        color: '#a855f7',
        badge: 'AGENTS',
        description: 'Screen potential destination agents against rigorous production, local experience, and client satisfaction standards.',
        primaryLink: { label: 'Agent Vetting', path: '/admin/dnn/agent-vetting' },
        links: [
          { label: '🛡️ Looking to Vette an Agent?', path: '/admin/dnn/agent-vetting', highlight: true },
          { label: '⭐ Active Relocation Agents', path: '/admin/active-relocation-agents' },
          { label: '📜 Top Relocation Agent Prospects', path: '/admin/roster' },
        ],
      },
      {
        id: 'lender_vetting_standards',
        title: 'Lender Selection & Vetting',
        tagline: 'Competitive rates, bridge loans, and escrow speed',
        icon: DollarSign,
        color: '#f59e0b',
        badge: 'LENDERS',
        description: 'Select and audit preferred relocation lenders offering competitive financing and nationwide coverage.',
        primaryLink: { label: 'Lender Vetting', path: '/admin/dnn/lender-vetting' },
        links: [
          { label: '🏦 Looking to Select a Lender?', path: '/admin/dnn/lender-vetting', highlight: true },
          { label: '💳 Financial Services Hub', path: '/financial-services' },
          { label: '🧮 Mortgage & Relo Calculator', path: '/calculator' },
        ],
      },
      {
        id: 'agreements_desk',
        title: 'PRN Referral Agreements Desk',
        tagline: 'Legally binding 25% referral and fee contracts',
        icon: FileCheck,
        color: '#D4AF37',
        badge: 'AGREEMENTS',
        description: 'Generate, issue, and archive executed 25% referral contracts between DysonRelo and brokerage firms.',
        primaryLink: { label: 'PRN Agreements', path: '/admin/prn-agreements' },
        links: [
          { label: '⚖️ PRN Agreements Generator', path: '/admin/prn-agreements', highlight: true },
          { label: '📜 Master Referral & Relo Mgmt Agreement', path: '/admin/master-agreement' },
          { label: '📥 Agreement Submissions Tracker', path: '/admin/agreement-submissions' },
        ],
      },
    ],
  },
  finance: {
    id: 'finance',
    name: 'Finance & Revenue Desk',
    subtitle: 'Featured agent revenue, render cost dashboards, and subscription billing',
    icon: DollarSign,
    accentColor: '#fbbf24',
    badge: 'FINANCIAL OPS',
    subChoices: [
      {
        id: 'revenue_hub',
        title: 'Featured Agent Revenue',
        tagline: 'Syndication fees, sponsorships, and referral payouts',
        icon: TrendingUp,
        color: '#fbbf24',
        badge: 'REVENUE',
        description: 'Monitor B2B revenue generated from morning broadcast sponsorships and co-branded distribution.',
        primaryLink: { label: 'Agent Revenue', path: '/admin/dnn/revenue' },
        links: [
          { label: '📈 Featured Agent Revenue', path: '/admin/dnn/revenue', highlight: true },
          { label: '📊 Finance Flow Chart', path: '/admin/workflows/finance' },
          { label: '🛡️ Escrow Management Desk', path: '/admin/wisdom/escrow' },
        ],
      },
      {
        id: 'cost_accounting',
        title: 'Production Cost Dashboard',
        tagline: 'Per-render API costs across HeyGen, Gemini & ElevenLabs',
        icon: BarChart3,
        color: '#10b981',
        badge: 'COSTS',
        description: 'Track granular video production expenses, average cost per broadcast, and monthly cloud compute.',
        primaryLink: { label: 'Cost Dashboard', path: '/admin/production-dashboard' },
        links: [
          { label: '📊 Production Cost Dashboard', path: '/admin/production-dashboard', highlight: true },
          { label: '⚡ Pipeline Credit Monitor', path: '/admin/heygen-credits' },
          { label: '🎬 Show Production Pipeline', path: '/admin/dnn/show-pipeline' },
        ],
      },
      {
        id: 'quotas_infrastructure',
        title: 'Pipeline Credit Monitor',
        tagline: 'HeyGen render credits, Grok tokens & TTS limits',
        icon: Zap,
        color: '#a855f7',
        badge: 'QUOTAS',
        description: 'Real-time monitoring of available rendering credits to ensure uninterrupted automated 6AM morning broadcasts.',
        primaryLink: { label: 'Credit Monitor', path: '/admin/heygen-credits' },
        links: [
          { label: '⚡ Pipeline Credit Monitor', path: '/admin/heygen-credits', highlight: true },
          { label: '📋 Interactive Business Plan', path: '/admin/business-plan' },
          { label: '📜 Dispatch Execution Log', path: '/admin/dispatch-log' },
        ],
      },
    ],
  },
};