import React, { useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
const LOGO_URL="https://media.base44.com/images/public/69d905d72ff7c93b5ef050c4/45d7c2c84_official-logo.png";
const HERO_URL="https://media.base44.com/images/public/69d905d72ff7c93b5ef050c4/efdc69af3_hero-evening-luxury-clean.png";
const SAMPLES=["742 Vista Del Mar","1844 Mountain Shadow Way","4220 Oak Hollow Terrace"];
export default function DysonHomesCopilot({initialPage}){
   const navigate=useNavigate(); const location=useLocation();
    const [address,setAddress]=useState("");
     const go=(v)=>{const a=(v||address||SAMPLES[0]).trim();navigate("/chat");};
      return <div style={{minHeight:"100vh",background:"#0a0a0a",color:"#e8e8e8",fontFamily:'Inter,"Segoe UI",system-ui,sans-serif'}}><section style={{padding:"4.5rem 40px 4rem"}}><div style={{maxWidth:1120,margin:"0 auto",display:"grid",gridTemplateColumns:"minmax(0,1.1fr) minmax(0,.9fr)",gap:56,alignItems:"center"}}><div><div style={{fontSize:11,letterSpacing:".14em",textTransform:"uppercase",color:"#777",marginBottom:"1.75rem"}}>Page 1 · Landing · Pure Text</div><div style={{display:"flex",flexDirection:"column",gap:8,marginBottom:"1.25rem"}}><span style={{fontFamily:"Georgia,serif",color:"#cfcfcf",letterSpacing:".08em"}}>meet</span><img src={LOGO_URL} alt="DysonHomes CoPilot" style={{display:"block",width:"min(480px,96%)",height:"auto"}}/></div><p style={{fontFamily:"Georgia,serif",fontSize:"1.1rem",color:"#e0e0e0",lineHeight:1.45,maxWidth:"22em",margin:"1rem 0 2.25rem"}}>The First Human Driven & Personal AI Real Estate Assistant</p><form onSubmit={e=>{e.preventDefault();go(address)}} style={{display:"flex",alignItems:"center",gap:10,background:"#F3F0E6",borderRadius:8,padding:"6px 6px 6px 16px",border:"1px solid #cfc8b8",maxWidth:540,marginBottom:"1rem"}}><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Paste MLS# or full street address" style={{flex:1,border:"none",background:"transparent",fontSize:15,color:"#171717",outline:"none",padding:"10px 4px"}}/><button style={{background:"#0a0a0a",color:"#eee",border:"1px solid #333",borderRadius:6,padding:"11px 18px",fontSize:14,fontWeight:600}}>Send</button></form><p style={{fontSize:13.5,color:"#a8a8a8",lineHeight:1.5,maxWidth:"36em"}}>Paste any address to see real comps, property risks, and your closing rebate  where allowed by law.</p><div style={{fontSize:12,color:"#888",marginBottom:8}}>Sample lookups</div><div style={{display:"flex",flexDirection:"column",alignItems:"flex-start",gap:6}}>{SAMPLES.map(x=><button key={x} onClick={()=>go(x)} style={{background:"#F3F0E6",color:"#171717",border:"1px solid #D4AF37",borderRadius:999,padding:"8px 14px",fontSize:13}}>{x}</button>)}</div><p style={{fontSize:12.5,color:"#888"}}>We are an independent research entity — no spam calls or agent involvement</p></div><div style={{borderRadius:12,overflow:"hidden",border:"1px solid #222"}}><img src={HERO_URL} alt="Evening luxury villa" style={{display:"block",width:"100%",height:"auto"}}/></div></div></section><section style={{maxWidth:1120,margin:"0 auto",padding:"0 40px 5rem"}}><h2 style={{fontFamily:"Georgia,serif",fontWeight:400}}>How Dyson Homes CoPilot Works</h2><ol style={{color:"#ccc",lineHeight:1.7}}><li><b>Paste Address</b> — Share the property details from your preferred MLS site.</li><li><b>AI + Human Analysis</b> — CoPilot analyzes with AI precision and human expertise.</li><li><b>Intelligence Delivered</b>  Comps, risks, and rebate insights in one private report.</li><li><b>Better Decisions</b>  Close with confidence. Keep more wealth.</li></ol></section></div>;
}
}